# Generated by Django 4.1.7 on 2023-02-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moment', models.DateTimeField()),
                ('key', models.CharField(max_length=1024)),
                ('value', models.FloatField()),
            ],
        ),
    ]
