# Generated by Django 4.1.7 on 2023-02-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_dataitem_offset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataitem',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
