# Generated by Django 4.1.7 on 2023-02-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_dataitem_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('formula', models.TextField()),
                ('min_alert_value', models.FloatField(null=True)),
                ('max_alert_value', models.FloatField(null=True)),
            ],
        ),
    ]
