# Generated by Django 4.1.7 on 2023-02-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_signal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='max_alert_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='min_alert_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
