# Generated by Django 4.1.7 on 2023-02-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_signal_max_alert_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TGChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TGMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_id', models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='signal',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
